language: python

python:
  - 3.5

sudo: false

install:
  - git clone https://git.launchpad.net/~sbeattie/apparmor/+git/apparmor
  - ln -s python-tools-setup.py apparmor/utils/setup.py
  - pip install -e apparmor/utils/
  - pip install -r tests/requirements.txt

script:
  - python setup.py nosetests -s

notifications:
  email: false
